import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import {Container, CssBaseline, ThemeProvider} from "@mui/material";
import darkTheme from "@/app/dark.theme";
import Header from "@/app/header/header";
import Providers from "@/app/providers";
import authenticated from "@/app/auth/authenticated";
import logout from "@/app/auth/logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = await authenticated();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers authenticated={isAuthenticated}>
          <CssBaseline />
          <Header logout={logout}/>
          <Container>{children}</Container>
        </Providers>
      </body>
    </html>
  );
}
